#!/bin/bash

cpu () {
sensors | grep "Core 0" | awk '{print $3}' | tr -d +
}

mix () {
amixer -c 1 get Master | grep Mono: | awk '{print $4}'| tr -d "[]%"
}


case $1 in
    cpu) cpu;;
    mix) mix;;
esac
